/* Local interaction state. No mask changes are treated as human acceptance. */
(() => {
  'use strict';
  const $=id=>document.getElementById(id), core=window.MaskCore;
  const token=document.querySelector('meta[name="editor-token"]').content;
  const history=new core.History(), canvases=[$('reference'),$('drawing')];
  const overlay=document.createElement('canvas'), oc=overlay.getContext('2d');
  let source, target, masks, originals, width, height, serverRevision=0, center, baseSpan;
  let ready=false, stroke=null, points=[], hover=null, holdOriginal=false, dirty=false, actionId=0;
  let timer, queue=Promise.resolve(), saveBlocked=false, savingVersion=false, lastVersion=null;
  const presets={full:[.5,.5,1],tree:[.3125,.296875,.625],upper:[.37890625,.1953125,.3125],middle:[.375,.328125,.375],lower:[.3046875,.48828125,.4375]};
  async function request(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:{'X-Mask-Editor-Token':token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok){let error;try{error=(await response.json()).error;}catch{error='Local save service unavailable';}throw Error(error);}return response;}
  function status(text,error=false){$('save-status').textContent=text;$('save-status').classList.toggle('error',error);}
  function snapshot(){return {source_packet_sha256:source.source_packet_sha256,masks:{building:core.pack(masks.building),valid:core.pack(masks.valid)}};}
  function enqueueSave(version=false){if(!ready||saveBlocked)return Promise.reject(Error('Saving is unavailable; download a backup before reloading.'));const data=snapshot(),id=actionId;if(version){savingVersion=true;$('save').disabled=true;status('Saving version…');}else status('Saving draft…');queue=queue.catch(()=>{}).then(async()=>{data.expected_revision=serverRevision;const result=await (await request(version?'/api/version':'/api/draft',data)).json();serverRevision=result.revision;if(id===actionId)dirty=false;if(version){lastVersion=result.version;$('download').disabled=dirty;$('saved-result').hidden=false;$('saved-path').textContent=result.output_directory;status(dirty?'Version saved; newer edits still need saving.':'Version saved on this laptop.');}else status(dirty?'Saving newer edits…':'Draft saved on this laptop.');return result;}).catch(error=>{saveBlocked=true;dirty=true;status(error.message+' Download an editable backup to keep your work.',true);throw error;}).finally(()=>{if(version){savingVersion=false;$('save').disabled=false;}});return queue;}
  function changed(){actionId++;dirty=true;$('download').disabled=true;$('saved-result').hidden=true;clearTimeout(timer);if(!saveBlocked)timer=setTimeout(()=>enqueueSave().catch(()=>{}),700);render();}
  function bounds(){const side=baseSpan/Number($('zoom').value);center=[Math.max(side/2,Math.min(width-side/2,center[0])),Math.max(side/2,Math.min(height-side/2,center[1]))];return [center[0]-side/2,center[1]-side/2,side];}
  const probe=document.createElement('span');probe.hidden=true;document.body.appendChild(probe);
  const colorCanvas=document.createElement('canvas');colorCanvas.width=colorCanvas.height=1;const cc=colorCanvas.getContext('2d',{willReadFrequently:true});
  function rgb(name){probe.style.color=`var(--${name})`;cc.fillStyle=getComputedStyle(probe).color;cc.fillRect(0,0,1,1);return [...cc.getImageData(0,0,1,1).data].slice(0,3);}
  function render(){if(!ready)return;const component=$('component').value,mask=masks[component],display=holdOriginal?'original':$('display').value;const tint=rgb(component==='building'?'red':'green'),added=rgb('yellow'),removed=rgb('purple'),alpha=Number($('opacity').value)/100;const image=oc.createImageData(width,height);let additions=0,removals=0;for(let i=0;i<mask.length;i++){const isAdded=mask[i]&&!originals[component][i],isRemoved=!mask[i]&&originals[component][i];additions+=isAdded?1:0;removals+=isRemoved?1:0;if(display==='binary'){const v=mask[i]?255:0;image.data.set([v,v,v,255],i*4);}else if($('changes').checked&&(isAdded||isRemoved))image.data.set([...(isAdded?added:removed),210],i*4);else if(mask[i])image.data.set([...tint,Math.round(alpha*255)],i*4);}oc.putImageData(image,0,0);const [x,y,side]=bounds();for(const canvas of canvases){const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(target,x,y,side,side,0,0,canvas.width,canvas.height);if(canvas.id==='drawing'&&display!=='original')ctx.drawImage(overlay,x,y,side,side,0,0,canvas.width,canvas.height);if(canvas.id==='drawing'){ctx.strokeStyle=`rgb(${tint.join(',')})`;ctx.lineWidth=2;if(points.length){ctx.beginPath();points.forEach((p,i)=>{const px=(p[0]-x)*canvas.width/side,py=(p[1]-y)*canvas.height/side;i?ctx.lineTo(px,py):ctx.moveTo(px,py);});if(hover)ctx.lineTo((hover[0]-x)*canvas.width/side,(hover[1]-y)*canvas.height/side);ctx.stroke();}if(hover&&['paint','erase'].includes($('tool').value)&&!holdOriginal){ctx.beginPath();ctx.arc((hover[0]+.5-x)*canvas.width/side,(hover[1]+.5-y)*canvas.height/side,Number($('brush').value)*canvas.width/side/2,0,Math.PI*2);ctx.stroke();}}}const building=component==='building';$('mask-caption').textContent=display==='binary'?'Exact mask · white = included':display==='original'?'Original · overlay hidden':building?'Building · red = included':'Validity · green = scored';$('mask-instruction').textContent=building?'Building: include visible walls, windows and entrances. Exclude leaves, cars and road.':'Validity: include pixels you can confidently label. Exclude uncertain foliage, hidden walls, cars and people.';$('tool-instruction').textContent=$('tool').value.startsWith('polygon')?'Click polygon corners on the right. Press Enter or Fill polygon; Esc cancels.':$('tool').value==='pan'?'Drag either image to move the zoomed view.':'Draw on the right image. The left stays unchanged. B = paint; E = erase.';$('brush-value').textContent=$('brush').value+' px';$('zoom-value').textContent=$('zoom').value+'×';$('opacity-value').textContent=$('opacity').value+'%';$('undo').disabled=!history.past.length;$('redo').disabled=!history.future.length;$('polygon-actions').hidden=points.length===0;$('close-polygon').disabled=points.length<3;$('edit-count').textContent=`${additions} added · ${removals} removed in this mask`;$('drawing').style.cursor=$('tool').value==='pan'?'grab':'crosshair';}
  function coordinate(event,canvas){const rect=canvas.getBoundingClientRect(),b=bounds();return [Math.max(0,Math.min(width-1,Math.floor(b[0]+(event.clientX-rect.left)*b[2]/rect.width))),Math.max(0,Math.min(height-1,Math.floor(b[1]+(event.clientY-rect.top)*b[2]/rect.height)))];}
  function finishStroke(){if(stroke?.kind==='draw')changed();stroke=null;}
  function finishPolygon(){if(points.length<3)return;history.push(masks);core.polygon(masks[$('component').value],width,height,points,$('tool').value==='polygon-erase'?0:1);points=[];changed();}
  for(const canvas of canvases){canvas.addEventListener('pointerdown',event=>{if(!ready||savingVersion)return;if(event.button!==0)return;if(canvas.id==='drawing')canvas.focus({preventScroll:true});const point=coordinate(event,canvas);if(canvas.id==='reference'||$('tool').value==='pan'){stroke={kind:'pan',start:[event.clientX,event.clientY],center:[...center],span:bounds()[2]};}else if($('tool').value.startsWith('polygon')){points.push(point);render();return;}else{if($('display').value==='original')$('display').value='overlay';history.push(masks);stroke={kind:'draw',last:point,component:$('component').value,value:$('tool').value==='erase'?0:1,diameter:Number($('brush').value)};core.stamp(masks[stroke.component],width,height,...point,stroke.diameter,stroke.value);render();}canvas.setPointerCapture(event.pointerId);});canvas.addEventListener('pointermove',event=>{if(!ready)return;hover=coordinate(event,canvas);$('position').textContent=`x=${hover[0]}, y=${hover[1]} · ${width} × ${height} pixels`;if(stroke?.kind==='draw'){core.line(masks[stroke.component],width,height,stroke.last,hover,stroke.diameter,stroke.value);stroke.last=hover;}else if(stroke?.kind==='pan'){const rect=canvas.getBoundingClientRect();center=[stroke.center[0]-(event.clientX-stroke.start[0])*stroke.span/rect.width,stroke.center[1]-(event.clientY-stroke.start[1])*stroke.span/rect.height];}render();});canvas.addEventListener('pointerup',finishStroke);canvas.addEventListener('pointercancel',finishStroke);canvas.addEventListener('pointerleave',()=>{hover=null;render();});}
  for(const id of ['component','tool','area'])$(id).addEventListener('change',()=>{finishStroke();points=[];if(id==='area'){const p=presets[$('area').value];center=[p[0]*width,p[1]*height];baseSpan=p[2]*Math.min(width,height);$('zoom').value=1;}render();});
  for(const id of ['brush','zoom','opacity','display','changes'])$(id).addEventListener('input',render);
  function undo(){const prior=history.undo(masks);if(prior){masks=prior;points=[];changed();}}
  function redo(){const next=history.redo(masks);if(next){masks=next;points=[];changed();}}
  $('undo').addEventListener('click',undo);$('redo').addEventListener('click',redo);
  $('close-polygon').addEventListener('click',finishPolygon);$('cancel-polygon').addEventListener('click',()=>{points=[];render();});
  $('save').addEventListener('click',()=>{clearTimeout(timer);if(points.length){status('Fill or cancel the current polygon before saving.',true);return;}enqueueSave(true).catch(()=>{});});
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  $('download').addEventListener('click',async()=>{if(!lastVersion)return;try{download(await (await request('/api/export/'+lastVersion)).blob(),'satground-'+lastVersion+'.zip');}catch(error){status(error.message,true);}});
  $('backup').addEventListener('click',()=>{if(ready)download(new Blob([JSON.stringify(snapshot())],{type:'application/json'}),'satground-editable-backup.json');});
  $('restore').addEventListener('change',async()=>{const file=$('restore').files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.source_packet_sha256!==source.source_packet_sha256)throw Error('Backup is for a different source image.');const restored={building:core.unpack(data.masks.building,width*height),valid:core.unpack(data.masks.valid,width*height)};history.push(masks);masks=restored;changed();}catch(error){status(error.message,true);}finally{$('restore').value='';}});
  document.addEventListener('keydown',event=>{if(!ready)return;if(event.ctrlKey||event.metaKey){if(event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?redo():undo();}if(event.key.toLowerCase()==='s'){event.preventDefault();$('save').click();}return;}if(['INPUT','SELECT','TEXTAREA'].includes(event.target.tagName))return;if(event.key.toLowerCase()==='o'){holdOriginal=true;render();}if(event.key==='Escape'){points=[];render();}if(event.key==='Enter'&&points.length){event.preventDefault();finishPolygon();}const tools={b:'paint',e:'erase',h:'pan'};if(tools[event.key.toLowerCase()]){$('tool').value=tools[event.key.toLowerCase()];points=[];render();}});
  document.addEventListener('keyup',event=>{if(event.key.toLowerCase()==='o'){holdOriginal=false;render();}});
  window.addEventListener('blur',()=>{holdOriginal=false;finishStroke();render();});
  window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
  new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['class','style','data-theme']});
  async function load(){try{source=await (await request('/api/state')).json();width=source.width;height=source.height;serverRevision=source.draft.revision;masks={building:core.unpack(source.draft.masks.building,width*height),valid:core.unpack(source.draft.masks.valid,width*height)};originals={building:core.unpack(source.original_masks.building,width*height),valid:core.unpack(source.original_masks.valid,width*height)};overlay.width=width;overlay.height=height;center=[width/2,height/2];baseSpan=Math.min(width,height);target=new Image();await new Promise((resolve,reject)=>{target.onload=resolve;target.onerror=reject;target.src=source.target;});ready=true;if(source.latest_version?.draft_revision===serverRevision){lastVersion=source.latest_version.version;$('download').disabled=false;$('saved-result').hidden=false;$('saved-path').textContent=source.latest_version.output_directory;}$('controls').disabled=false;$('backup').disabled=false;$('restore').disabled=false;status(source.draft.saved_utc?'Saved draft restored. Ready to continue.':'Ready to draw. Drafts save automatically.');render();}catch(error){status('Could not load the editor: '+error.message,true);}}
  load();
})();
