const assert = require('node:assert/strict');
const core = require('../src/satground/editor_ui/editor-core.js');
const mask = new Uint8Array(16 * 16);
core.stamp(mask, 16, 16, 4, 5, 1, 1);
assert.equal(mask.reduce((a,b)=>a+b,0), 1);
assert.equal(mask[5*16+4], 1);
core.line(mask,16,16,[4,5],[12,5],1,1);
for(let x=4;x<=12;x++) assert.equal(mask[5*16+x],1);
core.stamp(mask,16,16,4,5,1,0);
assert.equal(mask[5*16+4],0);
assert.deepEqual(core.unpack(core.pack(mask),mask.length),mask);
assert.throws(()=>core.unpack(core.pack(mask),999),/dimensions/);
const polygon=new Uint8Array(256);
core.polygon(polygon,16,16,[[2,2],[6,2],[6,6],[2,6]],1);
assert.equal(polygon.reduce((a,b)=>a+b,0),16);
const history=new core.History(2);
const masks={building:mask,valid:new Uint8Array(256).fill(1)};
history.push(masks);
core.stamp(masks.valid,16,16,8,8,1,0);
const beforeUndo=masks.valid.slice();
const undone=history.undo(masks);
assert.equal(undone.valid[8*16+8],1);
assert.deepEqual(undone.building,mask);
assert.deepEqual(history.redo(undone).valid,beforeUndo);
const originalBuilding=Uint8Array.from([1,0,0,0,0]);
const coverageMasks={building:Uint8Array.from([0,1,1,0,1]),valid:Uint8Array.from([1,1,0,1,0])};
const coverageBefore=core.clone(coverageMasks);
assert.deepEqual(core.scoringCoverage(coverageMasks,{building:originalBuilding}),{added:3,scored:1,excluded:2});
assert.deepEqual(coverageMasks,coverageBefore); // Reading coverage must never change either annotation.
coverageMasks.valid[2]=coverageMasks.valid[4]=1;
assert.deepEqual(core.scoringCoverage(coverageMasks,{building:originalBuilding}),{added:3,scored:3,excluded:0});
assert.deepEqual(core.scoringCoverage({building:originalBuilding,valid:originalBuilding},{building:originalBuilding}),{added:0,scored:0,excluded:0});
assert.throws(()=>core.scoringCoverage({building:originalBuilding,valid:new Uint8Array(3)},{building:originalBuilding}),/dimensions/);
console.log('Editor drawing, undo/redo, binary round-trip and independent scoring coverage passed.');
