const assert = require('node:assert/strict');
const core = require('../src/satground/editor_ui/editor-core.js');
const mask = new Uint8Array(16 * 16);
core.stamp(mask, 16, 16, 4, 5, 1, 1);
assert.equal(mask.reduce((a,b)=>a+b,0), 1);
assert.equal(mask[5*16+4], 1);
core.line(mask,16,16,[4,5],[12,5],1,1);
for(let x=4;x<=12;x++) assert.equal(mask[5*16+x],1);
core.stamp(mask,16,16,4,5,1,0);
assert.equal(mask[5*16+4],0);
assert.deepEqual(core.unpack(core.pack(mask),mask.length),mask);
assert.throws(()=>core.unpack(core.pack(mask),999),/dimensions/);
const polygon=new Uint8Array(256);
core.polygon(polygon,16,16,[[2,2],[6,2],[6,6],[2,6]],1);
assert.equal(polygon.reduce((a,b)=>a+b,0),16);
const history=new core.History(2);
const masks={building:mask,valid:new Uint8Array(256).fill(1)};
history.push(masks);
core.stamp(masks.valid,16,16,8,8,1,0);
const beforeUndo=masks.valid.slice();
const undone=history.undo(masks);
assert.equal(undone.valid[8*16+8],1);
assert.deepEqual(undone.building,mask);
assert.deepEqual(history.redo(undone).valid,beforeUndo);
console.log('Editor brush, continuous stroke, erase, polygon, binary round-trip and two-mask undo/redo passed.');
